In [113]:
import numpy as np

#可以用来计算原始矩阵的不为0的个数
def sum(Array):
    s = 0
    for i in range(Array.shape[0]):
        for j in range(Array.shape[1]):
            if Array[i][j]!=0:
                s = s+1
    return s  

#将arr矩阵里面的非零位置存放在列表里安
def none_list(Array):
    cow = 0
    li = []
    li0 = []
    for i in range(Array.shape[0]):
        ran = 0
        cow = cow+1
        for j in range(Array.shape[1]):
            ran = ran+1
            if Array[i][j]!=0:
                li0 = [cow,ran]
                li.append(li0)
    return np.array(li)  

#稀疏矩阵除了第一行外，将剩余的不为零的地方进行替换
def sparse_change(Array,sparse):
    for i in range(sum(Array)):
        sparse [i+1][0] = none_list(Array)[i][0]
        sparse [i+1][1] = none_list(Array)[i][1]
        sparse [i+1][2] = Array[none_list(Array)[i][0]-1][none_list(Array)[i][1]-1]
    return sparse

#初始化一个数组，arr为原始数组
arr = np.zeros((11,11),dtype = int)
arr[1][2] = arr[2][3] = 1

#初始化稀疏数组，sparseArray为稀疏数组，并对稀疏数组的第一行进行初始化
sparseArray = np.zeros((sum(arr)+1,3),dtype=int)
sparseArray[0][0] = arr.shape[0]
sparseArray[0][1] = arr.shape[1]
sparseArray[0][2] = sum(arr)

#将稀疏数组的其他行进行初始化
sparseArray = sparse_change(arr,sparseArray)
print(arr)
print()
print(sparseArray)

[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]

[[11 11  2]
 [ 2  3  1]
 [ 3  4  1]]
